In [1]:
a= 12


In [2]:
print(a)

12


In [3]:
def hellofunction():
    print("hello how ARE YOT")

In [4]:
hellofunction()

hello how ARE YOT


In [5]:
import numpy as np


In [9]:
print("lububu")


lububu


In [10]:
a = np.array([1,2,3,4,5,6,67])

In [11]:
a

array([ 1,  2,  3,  4,  5,  6, 67])

In [12]:
p = [ 2,4,5.6,4,3.90,54, " labubu" , True ]

In [13]:
np.array(p)

array(['2', '4', '5.6', '4', '3.9', '54', ' labubu', 'True'], dtype='<U32')

In [14]:
list1 = [[1,2,3,4] , [4,5,6,7], [7,8,9,0]]

In [18]:
list1

[[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9]]

In [19]:
np.array(list1)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [20]:
list2=np.array([[1,2,3,4] , [4,5,6,7], [7,8,9,0]])


In [21]:
list2


array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [7, 8, 9, 0]])

In [22]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

NameError: name 'arr' is not defined

In [25]:
arr

NameError: name 'arr' is not defined

In [26]:
np.zeros((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [28]:
np.ones((69,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1.

In [29]:
arr = np.linspace(1,100,2)

In [30]:
arr

array([  1., 100.])

In [32]:
np.linspace(1,1000,999)

array([   1.        ,    2.001002  ,    3.00200401,    4.00300601,
          5.00400802,    6.00501002,    7.00601202,    8.00701403,
          9.00801603,   10.00901804,   11.01002004,   12.01102204,
         13.01202405,   14.01302605,   15.01402806,   16.01503006,
         17.01603206,   18.01703407,   19.01803607,   20.01903808,
         21.02004008,   22.02104208,   23.02204409,   24.02304609,
         25.0240481 ,   26.0250501 ,   27.0260521 ,   28.02705411,
         29.02805611,   30.02905812,   31.03006012,   32.03106212,
         33.03206413,   34.03306613,   35.03406814,   36.03507014,
         37.03607214,   38.03707415,   39.03807615,   40.03907816,
         41.04008016,   42.04108216,   43.04208417,   44.04308617,
         45.04408818,   46.04509018,   47.04609218,   48.04709419,
         49.04809619,   50.0490982 ,   51.0501002 ,   52.0511022 ,
         53.05210421,   54.05310621,   55.05410822,   56.05511022,
         57.05611222,   58.05711423,   59.05811623,   60.05911

In [34]:
np.linspace(1,2,100000)

array([1.     , 1.00001, 1.00002, ..., 1.99998, 1.99999, 2.     ])

In [36]:
np.random.rand(9)

array([0.30839602, 0.09177584, 0.82988078, 0.39176441, 0.8417701 ,
       0.00384574, 0.68249865, 0.49142729, 0.6466464 ])

In [37]:
np.random.randn(17)

array([ 0.17657026, -1.92739253, -0.0242427 , -0.65555547, -0.39566257,
        2.01368191, -0.51894664, -1.34231064, -1.70289359, -0.20426287,
        1.58619352,  0.53005971, -0.99516917, -0.15058242, -0.45415856,
       -1.09866498,  0.18022613])

In [40]:
pd =np.random.randint(10,90,100)

array([76, 55, 39, 31, 40, 13, 85, 17, 29, 57, 66, 57, 76, 26, 14, 80, 79,
       51, 30, 30, 44, 21, 73, 86, 13, 44, 40, 70, 40, 28, 80, 36, 52, 23,
       49, 35, 27, 86, 78, 14, 21, 69, 12, 76, 89, 69, 51, 59, 83, 69, 38,
       60, 62, 26, 32, 67, 61, 35, 38, 76, 21, 49, 67, 28, 42, 53, 83, 15,
       33, 76, 28, 72, 57, 43, 84, 32, 54, 44, 58, 24, 44, 68, 54, 83, 22,
       30, 57, 43, 54, 71, 77, 41, 79, 82, 56, 29, 83, 10, 28, 34])

In [43]:
pd.info()

NameError: name 'pd' is not defined

In [50]:
ao =np.array([[1,2,3,4] ,[4,5,6,8] , [9,0,7 ,8]])
ao

array([[1, 2, 3, 4],
       [4, 5, 6, 8],
       [9, 0, 7, 8]])

In [52]:
ao.shape

(3, 4)

In [53]:
ao.size


12

In [54]:
ao.dtype

dtype('int32')

In [55]:
ao.min()

0

In [56]:
ao.max()

9

In [57]:
ao.sum()

57

In [58]:
ao.sum(0)

array([14,  7, 16, 20])

In [59]:
ao.sum(0,1,2)

TypeError: Cannot interpret '1' as a data type

In [61]:
ao.sum(1)ao.mean()

SyntaxError: invalid syntax (2703235499.py, line 1)

In [62]:
ao.mean()


4.75

In [63]:
ao.std()

2.802528620133373

In [65]:
ao.argmax()

8

In [66]:
ao


array([[1, 2, 3, 4],
       [4, 5, 6, 8],
       [9, 0, 7, 8]])

In [67]:
ao.argmin()


9

In [68]:
np.arange(1,90)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89])

In [73]:
app = np.arange(1,41)


In [74]:
app

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

In [75]:
app.reshape(3,8)

ValueError: cannot reshape array of size 40 into shape (3,8)

In [76]:
app.reshape(8,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [77]:
app = app.reshape(5,8)
app

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40]])

In [79]:
import numpy as n

In [81]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [83]:
arr[10]


11

In [84]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [85]:
arr[:-2]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [89]:
arr_slice = arr[::2]

arr_slice

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [90]:
arr_slice

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [94]:
ar = np.arange(1,41).reshape(4,5,2)

In [98]:
ar.reshape(4,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

In [103]:
ar[3]


array([[31, 32],
       [33, 34],
       [35, 36],
       [37, 38],
       [39, 40]])

In [105]:
ar2 = n.arange(1,91).reshape(5,18)

In [107]:
ar2[4]

array([73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
       90])

In [108]:
ar2[3,11]

66

In [109]:
ar2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
        53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
        71, 72],
       [73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88,
        89, 90]])

In [111]:
ar2[:2 , :5]

array([[ 1,  2,  3,  4,  5],
       [19, 20, 21, 22, 23]])

In [112]:
ar3 = n.arange(1,31).reshape(6,5)

In [113]:
ar3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [115]:
ar3[3: , 3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

ar3[:,3] 

In [116]:
ar3[: , 4]

array([ 5, 10, 15, 20, 25, 30])

In [117]:
ar4 = np.arange(1,21)

In [118]:

ar4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [121]:
ar5 = ar4[::1]

In [122]:
ar5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [123]:
bool_index = ar5%2==0

In [124]:
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [125]:
ar6 = n.array((ar5%2==0))

In [126]:
ar6

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [127]:
ar5 = ar5[bool_index]

In [128]:
ar5

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [129]:
ar1= n.array([1,2,3,4,5])

In [130]:
ar1

array([1, 2, 3, 4, 5])

In [131]:
ar2 = n.array([6,7,8,9,0])

In [132]:
ar2

array([6, 7, 8, 9, 0])

In [133]:
ar1+ar2

array([ 7,  9, 11, 13,  5])

In [134]:
ar1*ar2

array([ 6, 14, 24, 36,  0])

In [135]:
ar1?ar2

SyntaxError: invalid syntax (2873340563.py, line 1)

In [136]:
ar1/ar2

C:\Users\hp\AppData\Local\Temp\ipykernel_10808\54374712.py:1: RuntimeWarning: divide by zero encountered in divide
  ar1/ar2


array([0.16666667, 0.28571429, 0.375     , 0.44444444,        inf])

In [137]:
ar1**ar2

array([     1,    128,   6561, 262144,      1])

In [138]:
l =[10,20,30,40,50]
arr = n.array(l)

In [139]:
arr

array([10, 20, 30, 40, 50])

In [140]:
arr+10

array([20, 30, 40, 50, 60])

In [142]:
n.arange(1,101).reshape(10,10) +10

array([[ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110]])

In [143]:
a = n.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [144]:
sliced = a[:5]

In [145]:
sliced*45

array([ 45,  90, 135, 180, 225])

In [146]:
a[4:6]*1000

array([5000, 6000])

In [147]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [148]:
b =a


In [152]:
b[:8]*90

array([ 90, 180, 270, 360, 450, 540, 630, 720])

In [154]:
b[0]= 9000

In [155]:
b

array([9000,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20])

In [156]:
a

array([9000,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20])

In [157]:
##or
b = a.copy()
b[1] = 1000


In [158]:
a

array([9000,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20])

In [160]:
mat1 = n.arange(0,4).reshape(2,2)

In [161]:
mat2 = n.arange(5,9).reshape(2,2)

In [162]:
mat1+mat2

array([[ 5,  7],
       [ 9, 11]])

In [163]:
mat1+mat2

array([[ 5,  7],
       [ 9, 11]])

In [164]:
mat1@mat2

array([[ 7,  8],
       [31, 36]])

In [165]:
n.dot(mat1,mat2)

array([[ 7,  8],
       [31, 36]])

In [166]:
mat1.T

array([[0, 2],
       [1, 3]])

In [167]:
mat1.t

AttributeError: 'numpy.ndarray' object has no attribute 't'

In [175]:
mat1 = n.arange(1,5)



In [174]:
mat2 = n.arange(5,9)



# 

mat1

In [172]:
mat1

array([1, 2, 3])

## 

In [173]:
mat2

array([5, 6, 7])

In [178]:
n.vstack((mat1,mat2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [179]:
n.hstack((mat1,mat2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [180]:
n.column_stack((mat1,mat2))


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [186]:
m = n.arange(20).reshape(5,4)


In [187]:
m


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [189]:
n.hsplit(m,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19]])]

In [192]:
p= n.vsplit(m,5)

In [193]:
for i in p :
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
[[16 17 18 19]]


In [195]:
def expo(int num1 ,int num2):
    a = num1;
    for i in num2:
        a = a*a;
expo(2,2)

SyntaxError: invalid syntax (1994567289.py, line 1)

In [196]:
 p = n.arange(81).reshape(9,9)

In [197]:
p

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [198]:
p.sum()

3240

In [199]:
n.sum(p , axis=1)

array([ 36, 117, 198, 279, 360, 441, 522, 603, 684])

In [200]:
n.sum(p, axis=0)

array([324, 333, 342, 351, 360, 369, 378, 387, 396])

In [202]:
n.sum(p[0:3, 0:3])

90

In [208]:
for i in range(0,9,3):
    for j in range(0,9,3):
        a = p[i:i+3 , j:j+3]
        a.sum()

In [209]:
p.shape

(9, 9)

In [211]:
n.mean(p[: , 0:1])

36.0

In [212]:
p[:, 1:2]

array([[ 1],
       [10],
       [19],
       [28],
       [37],
       [46],
       [55],
       [64],
       [73]])

In [213]:
n.max(p[: , 1])

73

In [218]:
marks = p[: , 1] >70
marks

array([False, False, False, False, False, False, False, False,  True])

In [223]:
marks2 = p[ p[: , 1] >=80]

In [224]:
marks2

array([], shape=(0, 9), dtype=int32)

In [229]:
p[p[: , 2] >60]

array([[63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [234]:
p[: ,1] +=5 

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [232]:
p

array([ 6, 15, 24, 33, 42, 51, 60, 69, 78])

In [236]:
o = n.arange(100).reshape(10,10)

In [237]:
o

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [238]:
o[:,:]+5

array([[  5,   6,   7,   8,   9,  10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29,  30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39,  40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49,  50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59,  60,  61,  62,  63,  64],
       [ 65,  66,  67,  68,  69,  70,  71,  72,  73,  74],
       [ 75,  76,  77,  78,  79,  80,  81,  82,  83,  84],
       [ 85,  86,  87,  88,  89,  90,  91,  92,  93,  94],
       [ 95,  96,  97,  98,  99, 100, 101, 102, 103, 104]])

In [239]:
0

0

In [240]:
o

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [241]:
o[:,:]+=5

In [242]:
o

array([[  5,   6,   7,   8,   9,  10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29,  30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39,  40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49,  50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59,  60,  61,  62,  63,  64],
       [ 65,  66,  67,  68,  69,  70,  71,  72,  73,  74],
       [ 75,  76,  77,  78,  79,  80,  81,  82,  83,  84],
       [ 85,  86,  87,  88,  89,  90,  91,  92,  93,  94],
       [ 95,  96,  97,  98,  99, 100, 101, 102, 103, 104]])

In [246]:
len(o[o[:, 1] >15])

9

In [249]:
n.average(o[: ,1:3],axis=0)

array([51., 52.])

In [253]:
o[(o[:, 1]>=80) & (o[:,2]>=80)]

array([[ 85,  86,  87,  88,  89,  90,  91,  92,  93,  94],
       [ 95,  96,  97,  98,  99, 100, 101, 102, 103, 104]])

In [262]:
o[:,2][o[:,2]<90] =0

In [263]:
o

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 85,  86,   0,  88,  89,  90,  91,  92,  93,  94],
       [ 95,  96,  97,  98,  99, 100, 101, 102, 103, 104]])

In [264]:
d = n.arange(100).reshape(10,10)

In [265]:
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [267]:
d[:,2][d[:, 2]<80]=0

In [268]:
d

array([[ 0,  1,  0,  3,  4,  5,  6,  7,  8,  9],
       [10, 11,  0, 13, 14, 15, 16, 17, 18, 19],
       [20, 21,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 31,  0, 33, 34, 35, 36, 37, 38, 39],
       [40, 41,  0, 43, 44, 45, 46, 47, 48, 49],
       [50, 51,  0, 53, 54, 55, 56, 57, 58, 59],
       [60, 61,  0, 63, 64, 65, 66, 67, 68, 69],
       [70, 71,  0, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])